import { Artifact, ShipSkin, Contract, SkyPassTier } from '../types';

export const INITIAL_ARTIFACTS: Artifact[] = [
  {
    id: 'ancient_thruster',
    name: { ar: 'دافع قديم', en: 'Ancient Thruster' },
    description: { ar: 'يزيد سرعة السفينة بشكل دائم بنسبة 5%', en: 'Permanently increases ship speed by 5%' },
    icon: '🚀',
    rarity: 'common',
    isRestored: false,
    restorationCost: 300,
    starCost: 12,
    buff: { type: 'speedMultiplier', value: 0.05 }
  },
  {
    id: 'void_magnet',
    name: { ar: 'مغناطيس الفراغ', en: 'Void Magnet' },
    description: { ar: 'يزيد مدى المغناطيس بنسبة 15%', en: 'Increases magnet range by 15%' },
    icon: '🧲',
    rarity: 'rare',
    isRestored: false,
    restorationCost: 800,
    starCost: 30,
    buff: { type: 'magnetRangeBoost', value: 0.15 }
  },
  {
    id: 'stellar_core',
    name: { ar: 'نواة نجمية', en: 'Stellar Core' },
    description: { ar: 'يزيد قيمة النجوم بنسبة 10%', en: 'Increases star value by 10%' },
    icon: '💎',
    rarity: 'epic',
    isRestored: false,
    restorationCost: 1500,
    starCost: 60,
    buff: { type: 'starValueMultiplier', value: 0.10 }
  },
  {
    id: 'eternal_shield',
    name: { ar: 'درع أبدي', en: 'Eternal Shield' },
    description: { ar: 'يزيد مدة الدرع بنسبة 20%', en: 'Increases shield duration by 20%' },
    icon: '🛡️',
    rarity: 'legendary',
    isRestored: false,
    restorationCost: 3000,
    starCost: 120,
    buff: { type: 'shieldDurationBoost', value: 0.20 }
  }
];

export const INITIAL_SKINS: ShipSkin[] = [
  {
    id: 'default_ship',
    name: { ar: 'السفينة القياسية', en: 'Standard Ship' },
    description: { ar: 'السفينة الأساسية للاتحاد', en: 'The basic Federation ship' },
    cost: 0,
    rarity: 'common',
    isUnlocked: true,
    previewColor: '#6366f1'
  },
  {
    id: 'neon_raider',
    name: { ar: 'المتسلل النيوني', en: 'Neon Raider' },
    description: { ar: 'سفينة سريعة ومضيئة', en: 'A fast and glowing ship' },
    cost: 1000,
    starCost: 24,
    rarity: 'rare',
    isUnlocked: false,
    previewColor: '#10b981',
    ability: { ar: 'فرصة 5% لتفادي الاصطدام تلقائياً', en: '5% chance to auto-dodge collision' }
  },
  {
    id: 'crimson_fury',
    name: { ar: 'الغضب القرمزي', en: 'Crimson Fury' },
    description: { ar: 'سفينة هجومية ثقيلة', en: 'A heavy assault ship' },
    cost: 2500,
    starCost: 72,
    rarity: 'epic',
    isUnlocked: false,
    previewColor: '#ef4444',
    ability: { ar: 'تبدأ كل جولة بكويكب ناري واحد', en: 'Start every round with 1 Fire Asteroid' }
  },
  {
    id: 'golden_monarch',
    name: { ar: 'العاهل الذهبي', en: 'Golden Monarch' },
    description: { ar: 'سفينة الملوك والنبلاء', en: 'The ship of kings and nobles' },
    cost: 6000,
    starCost: 180,
    rarity: 'legendary',
    isUnlocked: false,
    previewColor: '#f59e0b',
    ability: { ar: 'مضاعف عملات دائم x1.5', en: 'Permanent x1.5 coin multiplier' }
  }
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'scout_agreement',
    name: { ar: 'اتفاقية المستكشف', en: "Scout's Agreement" },
    description: { ar: 'حقق 2000 نقطة في جولة واحدة', en: 'Reach 2000 points in a single run' },
    cost: 300,
    starCost: 6,
    reward: 500,
    type: 'score',
    targetValue: 2000,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'easy'
  },
  {
    id: 'collector_license',
    name: { ar: 'رخصة الجامع', en: "Collector's License" },
    description: { ar: 'اجمع 500 نجمة تراكمياً', en: 'Collect 500 stars cumulatively' },
    cost: 500,
    starCost: 12,
    reward: 750,
    type: 'stars',
    targetValue: 500,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'easy'
  },
  {
    id: 'endurance_pact',
    name: { ar: 'ميثاق التحمل', en: 'Endurance Pact' },
    description: { ar: 'ابقَ على قيد الحياة لمدة 60 ثانية في جولة واحدة', en: 'Survive for 60 seconds in a single run' },
    cost: 1000,
    starCost: 24,
    reward: 1500,
    type: 'time',
    targetValue: 60,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'medium'
  },
  {
    id: 'precision_protocol',
    name: { ar: 'بروتوكول الدقة', en: 'Precision Protocol' },
    description: { ar: 'قم بـ 10 مراوغات قريبة في جولة واحدة', en: 'Perform 10 Near-Misses in a single run' },
    cost: 1500,
    starCost: 36,
    reward: 2200,
    type: 'near_miss',
    targetValue: 10,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'medium'
  },
  {
    id: 'stardust_venture',
    name: { ar: 'مشروع غبار النجوم', en: 'Stardust Venture' },
    description: { ar: 'مضاعف قيمة النجوم x1.2 لـ 5 جولات قادمة', en: 'x1.2 Star Value multiplier for the next 5 games' },
    cost: 2000,
    starCost: 48,
    reward: 2800,
    type: 'investment',
    targetValue: 5,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'medium',
    duration: 5,
    remainingGames: 5
  },
  {
    id: 'void_risk',
    name: { ar: 'مخاطرة الفراغ', en: 'Void Risk' },
    description: { ar: 'حقق 5000 نقطة (تزداد السرعة أسرع بنسبة 10%)', en: 'Reach 5000 points (Speed increases 10% faster)' },
    cost: 3000,
    starCost: 72,
    reward: 4500,
    type: 'risk',
    targetValue: 5000,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'hard'
  },
  {
    id: 'market_insight',
    name: { ar: 'رؤية السوق', en: 'Market Insight' },
    description: { ar: 'خصم 10% على ترقيات المصنع لـ 24 ساعة', en: '10% discount on Forge upgrades for 24 hours' },
    cost: 5000,
    starCost: 120,
    reward: 7000,
    type: 'investment',
    targetValue: 86400000,
    currentValue: 0,
    isPurchased: false,
    isCompleted: false,
    isClaimed: false,
    rarity: 'hard',
    duration: 86400000,
    remainingGames: 5
  }
];


export const SKY_PASS_TIERS: SkyPassTier[] = [
  { level: 1, requiredExp: 100, reward: { type: 'coins', amount: 25 }, proReward: { type: 'stars', amount: 20 }, task: { ar: 'اجمع 100 نقطة خبرة للبدء', en: 'Earn 100 EXP to start' }, isClaimed: false, isProClaimed: false },
  { level: 2, requiredExp: 250, reward: { type: 'powerup', id: 'shield' }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'العب جولة واحدة على الأقل', en: 'Play at least one round' }, isClaimed: false, isProClaimed: false },
  { level: 3, requiredExp: 500, reward: { type: 'stars', amount: 30 }, proReward: { type: 'powerup', id: 'doublePoints' }, task: { ar: 'اجمع 50 نجمة في جولة واحدة', en: 'Collect 50 stars in one run' }, isClaimed: false, isProClaimed: false },
  { level: 4, requiredExp: 800, reward: { type: 'coins', amount: 25 }, proReward: { type: 'stardust', amount: 100 }, task: { ar: 'ابقَ على قيد الحياة لمدة 30 ثانية', en: 'Survive for 30 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 5, requiredExp: 1200, reward: { type: 'stardust', amount: 50 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'حقق 1000 نقطة', en: 'Reach 1000 points' }, isClaimed: false, isProClaimed: false },
  { level: 6, requiredExp: 1700, reward: { type: 'powerup', id: 'magnet' }, proReward: { type: 'stars', amount: 50 }, task: { ar: 'قم بـ 3 مراوغات قريبة', en: 'Perform 3 near-misses' }, isClaimed: false, isProClaimed: false },
  { level: 7, requiredExp: 2300, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'slowMotion' }, task: { ar: 'استخدم قدرة خاصة واحدة', en: 'Use one special power-up' }, isClaimed: false, isProClaimed: false },
  { level: 8, requiredExp: 3000, reward: { type: 'stars', amount: 60 }, proReward: { type: 'stardust', amount: 200 }, task: { ar: 'اجمع 200 نجمة تراكمياً', en: 'Collect 200 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 9, requiredExp: 3800, reward: { type: 'powerup', id: 'fireAsteroid', amount: 5 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'دمر مركبة فضائية واحدة', en: 'Destroy one spaceship' }, isClaimed: false, isProClaimed: false },
  { level: 10, requiredExp: 5000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'skin', id: 'neon_raider' }, task: { ar: 'وصل إلى القطاع الثاني', en: 'Reach Sector 2' }, isClaimed: false, isProClaimed: false },
  { level: 11, requiredExp: 6500, reward: { type: 'stardust', amount: 150 }, proReward: { type: 'stars', amount: 100 }, task: { ar: 'حقق 1500 نقطة', en: 'Reach 1500 points' }, isClaimed: false, isProClaimed: false },
  { level: 12, requiredExp: 8000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'shield', amount: 3 }, task: { ar: 'اجمع 100 نجمة في جولة واحدة', en: 'Collect 100 stars in one run' }, isClaimed: false, isProClaimed: false },
  { level: 13, requiredExp: 10000, reward: { type: 'stars', amount: 80 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'ابقَ على قيد الحياة لـ 60 ثانية', en: 'Survive for 60 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 14, requiredExp: 12500, reward: { type: 'powerup', id: 'magnet', amount: 2 }, proReward: { type: 'stardust', amount: 300 }, task: { ar: 'قم بـ 10 مراوغات قريبة', en: 'Perform 10 near-misses' }, isClaimed: false, isProClaimed: false },
  { level: 15, requiredExp: 15000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'artifact', id: 'ancient_thruster' }, task: { ar: 'حقق 2000 نقطة', en: 'Reach 2000 points' }, isClaimed: false, isProClaimed: false },
  { level: 16, requiredExp: 18000, reward: { type: 'stardust', amount: 200 }, proReward: { type: 'stars', amount: 150 }, task: { ar: 'اجمع 1000 نجمة تراكمياً', en: 'Collect 1000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 17, requiredExp: 21000, reward: { type: 'powerup', id: 'slowMotion', amount: 2 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'دمر 5 مركبات فضائية', en: 'Destroy 5 spaceships' }, isClaimed: false, isProClaimed: false },
  { level: 18, requiredExp: 25000, reward: { type: 'stars', amount: 100 }, proReward: { type: 'stardust', amount: 400 }, task: { ar: 'ابقَ على قيد الحياة لـ 90 ثانية', en: 'Survive for 90 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 19, requiredExp: 30000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'fireAsteroid', amount: 10 }, task: { ar: 'حقق 3500 نقطة', en: 'Reach 3500 points' }, isClaimed: false, isProClaimed: false },
  { level: 20, requiredExp: 36000, reward: { type: 'stardust', amount: 300 }, proReward: { type: 'stars', amount: 200 }, task: { ar: 'العب 10 جولات إجمالاً', en: 'Play 10 rounds total' }, isClaimed: false, isProClaimed: false },
  { level: 21, requiredExp: 43000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'shield', amount: 5 }, task: { ar: 'اجمع 300 نجمة في جولة واحدة', en: 'Collect 300 stars in one run' }, isClaimed: false, isProClaimed: false },
  { level: 22, requiredExp: 51000, reward: { type: 'stars', amount: 150 }, proReward: { type: 'stardust', amount: 500 }, task: { ar: 'ابقَ على قيد الحياة لـ 120 ثانية', en: 'Survive for 120 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 23, requiredExp: 60000, reward: { type: 'powerup', id: 'magnet', amount: 5 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'قم بـ 15 مراوغة قريبة', en: 'Perform 15 near-misses' }, isClaimed: false, isProClaimed: false },
  { level: 24, requiredExp: 70000, reward: { type: 'stardust', amount: 400 }, proReward: { type: 'stars', amount: 300 }, task: { ar: 'حقق 5000 نقطة', en: 'Reach 5000 points' }, isClaimed: false, isProClaimed: false },
  { level: 25, requiredExp: 82000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'skin', id: 'crimson_fury' }, task: { ar: 'وصل إلى القطاع الثالث', en: 'Reach Sector 3' }, isClaimed: false, isProClaimed: false },
  { level: 26, requiredExp: 95000, reward: { type: 'stars', amount: 200 }, proReward: { type: 'stardust', amount: 600 }, task: { ar: 'اجمع 2000 نجمة تراكمياً', en: 'Collect 2000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 27, requiredExp: 110000, reward: { type: 'powerup', id: 'slowMotion', amount: 5 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'دمر 10 مركبة فضائية', en: 'Destroy 10 spaceships' }, isClaimed: false, isProClaimed: false },
  { level: 28, requiredExp: 127000, reward: { type: 'stardust', amount: 500 }, proReward: { type: 'stars', amount: 400 }, task: { ar: 'حقق 7500 نقطة', en: 'Reach 7500 points' }, isClaimed: false, isProClaimed: false },
  { level: 29, requiredExp: 146000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'fireAsteroid', amount: 20 }, task: { ar: 'العب 25 جولة إجمالاً', en: 'Play 25 rounds total' }, isClaimed: false, isProClaimed: false },
  { level: 30, requiredExp: 167000, reward: { type: 'stars', amount: 300 }, proReward: { type: 'stardust', amount: 800 }, task: { ar: 'حقق 10000 نقطة', en: 'Reach 10000 points' }, isClaimed: false, isProClaimed: false },
  { level: 31, requiredExp: 190000, reward: { type: 'stardust', amount: 600 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'اجمع 500 نجمة في جولة واحدة', en: 'Collect 500 stars in one run' }, isClaimed: false, isProClaimed: false },
  { level: 32, requiredExp: 215000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'stars', amount: 500 }, task: { ar: 'ابقَ على قيد الحياة لـ 120 ثانية', en: 'Survive for 120 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 33, requiredExp: 242000, reward: { type: 'stars', amount: 400 }, proReward: { type: 'stardust', amount: 1000 }, task: { ar: 'قم بـ 30 مراوغة قريبة', en: 'Perform 30 near-misses' }, isClaimed: false, isProClaimed: false },
  { level: 34, requiredExp: 271000, reward: { type: 'powerup', id: 'shield', amount: 10 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'حقق 15000 نقطة', en: 'Reach 15000 points' }, isClaimed: false, isProClaimed: false },
  { level: 35, requiredExp: 302000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'artifact', id: 'void_magnet' }, task: { ar: 'اجمع 5000 نجمة تراكمياً', en: 'Collect 5000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 36, requiredExp: 335000, reward: { type: 'stardust', amount: 800 }, proReward: { type: 'stars', amount: 600 }, task: { ar: 'دمر 25 مركبة فضائية', en: 'Destroy 25 spaceships' }, isClaimed: false, isProClaimed: false },
  { level: 37, requiredExp: 370000, reward: { type: 'stars', amount: 500 }, proReward: { type: 'stardust', amount: 1200 }, task: { ar: 'حقق 20000 نقطة', en: 'Reach 20000 points' }, isClaimed: false, isProClaimed: false },
  { level: 38, requiredExp: 407000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'powerup', id: 'magnet', amount: 10 }, task: { ar: 'العب 25 جولة إجمالاً', en: 'Play 25 rounds total' }, isClaimed: false, isProClaimed: false },
  { level: 39, requiredExp: 446000, reward: { type: 'stardust', amount: 1000 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'حقق 25000 نقطة', en: 'Reach 25000 points' }, isClaimed: false, isProClaimed: false },
  { level: 40, requiredExp: 487000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'stars', amount: 1000 }, task: { ar: 'اجمع 10000 نجمة تراكمياً', en: 'Collect 10000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 41, requiredExp: 530000, reward: { type: 'stars', amount: 600 }, proReward: { type: 'stardust', amount: 1500 }, task: { ar: 'ابقَ على قيد الحياة لـ 180 ثانية', en: 'Survive for 180 seconds' }, isClaimed: false, isProClaimed: false },
  { level: 42, requiredExp: 575000, reward: { type: 'stardust', amount: 1200 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'قم بـ 60 مراوغة قريبة', en: 'Perform 60 near-misses' }, isClaimed: false, isProClaimed: false },
  { level: 43, requiredExp: 622000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'stars', amount: 1200 }, task: { ar: 'حقق 40000 نقطة', en: 'Reach 40000 points' }, isClaimed: false, isProClaimed: false },
  { level: 44, requiredExp: 671000, reward: { type: 'powerup', id: 'slowMotion', amount: 10 }, proReward: { type: 'stardust', amount: 2000 }, task: { ar: 'دمر 50 مركبة فضائية', en: 'Destroy 50 spaceships' }, isClaimed: false, isProClaimed: false },
  { level: 45, requiredExp: 722000, reward: { type: 'stardust', amount: 1500 }, proReward: { type: 'coins', amount: 75 }, task: { ar: 'اجمع 25000 نجمة تراكمياً', en: 'Collect 25000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 46, requiredExp: 775000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'stars', amount: 1500 }, task: { ar: 'حقق 50000 نقطة', en: 'Reach 50000 points' }, isClaimed: false, isProClaimed: false },
  { level: 47, requiredExp: 830000, reward: { type: 'stars', amount: 1000 }, proReward: { type: 'stardust', amount: 3000 }, task: { ar: 'العب 50 جولة إجمالاً', en: 'Play 50 rounds total' }, isClaimed: false, isProClaimed: false },
  { level: 48, requiredExp: 887000, reward: { type: 'stardust', amount: 2000 }, proReward: { type: 'coins', amount: 100 }, task: { ar: 'حقق 75000 نقطة', en: 'Reach 75000 points' }, isClaimed: false, isProClaimed: false },
  { level: 49, requiredExp: 946000, reward: { type: 'coins', amount: 30 }, proReward: { type: 'stars', amount: 2000 }, task: { ar: 'اجمع 50000 نجمة تراكمياً', en: 'Collect 50000 stars cumulatively' }, isClaimed: false, isProClaimed: false },
  { level: 50, requiredExp: 1000000, reward: { type: 'stars', amount: 5000 }, proReward: { type: 'skin', id: 'golden_monarch' }, task: { ar: 'حقق 100000 نقطة', en: 'Reach 100000 points' }, isClaimed: false, isProClaimed: false },
];

